# Backend (Flask + CrewAI)
FROM python:3.11-slim

WORKDIR /app

COPY ./src ./src
COPY ./src/analista_licitacoes/main.py ./main.py
COPY requirements.txt ./
COPY .env ./

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "main.py"]
